FROM php:5.6-fpm

#安装扩展

#安装oracle扩展需要的文件
COPY ./extensions/oci8 /opt/

RUN \
  apt-get update \
  # 安装源码包里面的扩展
  && docker-php-ext-install -j$(nproc) bcmath pdo_mysql \
  #安装gd库
  # && apt-get install -y libfreetype6-dev libpng-dev libjpeg62-turbo-dev \
  # && docker-php-ext-install -j$(nproc) gd \
  #安装xdebug扩展
  && cd /opt && curl -o xdebug-2.4.0.tgz http://pecl.php.net/get/xdebug-2.4.0.tgz && tar -zxvf xdebug-2.4.0.tgz && cd xdebug-2.4.0 && phpize && ./configure && make && make install &&  docker-php-ext-enable xdebug \
  #安装redis扩展
  && cd /opt && curl -o redis-4.3.0.tgz  http://pecl.php.net/get/redis-4.3.0.tgz && tar -zxvf redis-4.3.0.tgz && cd redis-4.3.0 && phpize && ./configure && make && make install && docker-php-ext-enable redis \
  # && pecl install redis xdebug-2.4.0 && docker-php-ext-enable redis xdebug \
  #安装oracle扩展, 如果不需要请注释掉
  && sh /opt/install-oci8.sh